apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adcp-profiler-service.fullname" . }}-config
  labels:
    {{- include "adcp-profiler-service.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
