{{- $fullName := include "adcp-profiler-service.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: adcp-profiler-service
  labels:
    {{- include "adcp-profiler-service.labels" . | nindent 4 }}
spec:
  selector:
    name: {{ include "adcp-profiler-service.fullname" . }}
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: {{ .Values.config.port }}
